version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: bycecles_admin
      MONGO_INITDB_ROOT_PASSWORD: bycecles_password
      MONGO_INITDB_DATABASE: test
    restart: always

volumes:
  mongodb_data:
    driver: local
